<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Carbon\Carbon;


class PaisTableSeeder extends Seeder
{
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('pais')->truncate();
        Schema::enableForeignKeyConstraints();

        $paises = [
            ['nome' => 'Afghanistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Åland Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Albania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Algeria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'American Samoa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Andorra', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Angola', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Anguilla', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Antarctica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Antigua and Barbuda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Argentina', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Armenia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Aruba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Australia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Austria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Azerbaijan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bahamas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bahrain', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bangladesh', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Barbados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Belarus', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Belgium', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Belize', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Benin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bermuda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bhutan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bolivia, Plurinational State of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bonaire, Sint Eustatius and Saba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bosnia and Herzegovina', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Botswana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bouvet Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Brazil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'British Indian Ocean Territory', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Brunei Darussalam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Bulgaria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Burkina Faso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Burundi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cambodia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cameroon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Canada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cape Verde', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cayman Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Central African Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Chad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Chile', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'China', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Christmas Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cocos (Keeling) Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Colombia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Comoros', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Congo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Congo, the Democratic Republic of the', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cook Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Costa Rica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Côte d\'Ivoire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Croatia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cuba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Curaçao', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Cyprus', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Czech Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Denmark', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Djibouti', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Dominica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Dominican Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Ecuador', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Egypt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'El Salvador', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Equatorial Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Eritrea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Estonia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Ethiopia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Falkland Islands (Malvinas)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Faroe Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Fiji', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Finland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'France', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'French Guiana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'French Polynesia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'French Southern Territories', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Gabon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Gambia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Georgia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Germany', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Ghana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Gibraltar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Greece', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Greenland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Grenada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guadeloupe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guatemala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guernsey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guinea-Bissau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Guyana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Haiti', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Heard Island and McDonald Mcdonald Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Holy See (Vatican City State)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Honduras', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Hong Kong', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Hungary', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Iceland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'India', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Indonesia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Iran, Islamic Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Iraq', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Ireland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Isle of Man', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Israel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Italy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Jamaica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Japan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Jersey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Jordan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Kazakhstan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Kenya', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Kiribati', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Korea, Democratic People\'s Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Korea, Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Kuwait', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Kyrgyzstan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Lao People\'s Democratic Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Latvia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Lebanon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Lesotho', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Liberia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Libya', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Liechtenstein', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Lithuania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Luxembourg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Macao', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Macedonia, the Former Yugoslav Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Madagascar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Malawi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Malaysia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Maldives', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mali', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Malta', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Marshall Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Martinique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mauritania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mauritius', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mayotte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mexico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Micronesia, Federated States of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Moldova, Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Monaco', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mongolia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Montenegro', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Montserrat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Morocco', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Mozambique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Myanmar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Namibia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Nauru', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Nepal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Netherlands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'New Caledonia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'New Zealand', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Nicaragua', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Niger', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Nigeria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Niue', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Norfolk Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Northern Mariana Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Norway', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Oman', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Pakistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Palau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Palestine, State of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Panama', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Papua New Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Paraguay', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Peru', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Philippines', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Pitcairn', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Poland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Portugal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Puerto Rico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Qatar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Réunion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Romania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Russian Federation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Rwanda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Barthélemy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Helena, Ascension and Tristan da Cunha', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Kitts and Nevis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Lucia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Martin (French part)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Pierre and Miquelon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saint Vincent and the Grenadines', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Samoa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'San Marino', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sao Tome and Principe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Saudi Arabia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Senegal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Serbia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Seychelles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sierra Leone', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Singapore', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sint Maarten (Dutch part)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Slovakia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Slovenia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Solomon Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Somalia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'South Africa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'South Georgia and the South Sandwich Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'South Sudan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Spain', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sri Lanka', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sudan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Surinome', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Svalbard and Jan Mayen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Swaziland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Sweden', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Switzerland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Syrian Arab Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Taiwan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tajikistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tanzania, United Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Thailand', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Timor-Leste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Togo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tokelau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tonga', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Trinidad and Tobago', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tunisia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Turkey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Turkmenistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Turks and Caicos Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Tuvalu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Uganda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Ukraine', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'United Arab Emirates', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'United Kingdom', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'United States', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'United States Minor Outlying Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Uruguay', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Uzbekistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Vanuatu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Venezuela, Bolivarian Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Viet Nam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Virgin Islands, British', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Virgin Islands, U.S.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Wallis and Futuna', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Western Sahara', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Yemen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Zambia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'Zimbabwe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        DB::table('pais')->insert($paises);
    }
}
